@Basket_HostAddress = https://localhost:7160


POST {{Basket_HostAddress}}/basket
Content-Type: application/json
{
  "username": "farooq",
  "items": [
    {
      "price": 999.99,
      "quantity": 1
    },
    {
      "price": 49.99,
      "quantity": 2
    },
    {
      "price": 199.99,
      "quantity": 1
    }
  ]
}

###

GET {{Basket_HostAddress}}/basket/farooq
Accept: application/json

###

PUT {{Basket_HostAddress}}/basket
Content-Type: application/json
{
  "username": "farooq",
  "items": [
    {
      "price": 999.99,
      "quantity": 2
    },
    {
      "price": 49.99,
      "quantity": 4
    },
    {
      "price": 199.99,
      "quantity": 2
    }
  ]
}

###

DELETE {{Basket_HostAddress}}/basket/farooq
Accept: application/json

